### PR TITLE
Vacation favorite spots

### PR DESCRIPTION
**Pull request by jordanmccullough**
Please contribute any ideas and favorite locations. This means you, @githubschool/new-hubbers .

@githubteacher, FYI on this effort with the new hires.

- [x] Minimum of three US states
- [x] Two continents

### CODE REVIEW

**Comment by jordanmccullough** [comment]
Looks like we're almost there. Have the three state listed minimum requirements.

**Comment by jordanmccullough** [comment]
@k8d, How about another US state added to the list? Perhaps Florida?

**Comment by k8d** [comment]
@jordanmccullough, you got it

**Comment by jordanmccullough** [comment]
Hey all, did we see my list of ideas over here? https://github.com/githubschool/bootcamp/issues/4

**Comment by jordanmccullough** [comment]
yoda

**Comment by jordanmccullough** [comment]
:+1: :ship: :shipit:

**Pull request merged**
